# -*- coding: utf-8 -*-
"""
MultiTools Hub - Programmatic SEO Database
Provides detailed guides, technical breakdowns, use cases, and FAQs
for all tool categories and tools.
"""

from image_content import IMAGE_SEO_DATA

# Category introductions and descriptions
CATEGORY_INFO = {
    "css": {
        "intro": "Enhance your front-end styling workflow with our suite of modern CSS designers and layout tools. These utilities are crafted to help web designers and developers generate clean, standards-compliant CSS styling values in real-time, removing the guesswork from modern layouts.",
        "tech_details": "Every layout visualizer and styling tool executes 100% in your local browser window. They utilize modern web APIs and HTML5 Canvas objects to generate and preview styles immediately. This client-side execution means you can style, tweak, and copy code without lag or server dependencies.",
        "use_cases": [
            "Designing responsive grid and flexbox layouts visually before writing boilerplate code.",
            "Creating consistent modern visual effects (like soft drop shadows, gradients, and custom button triggers).",
            "Converting color spaces (HEX, RGB, HSL) quickly for design specification compliance."
        ],
        "faqs": [
            ("Are these CSS classes compatible with all modern browsers?", "Yes, the CSS styles generated by our tools adhere to standard W3C specifications. When using advanced attributes like gradients or shadows, standard styles are output that work across Chrome, Safari, Firefox, and Edge."),
            ("Can I use these visual layout helpers for responsive design?", "Absolutely. Tools like our Flexbox and Grid layout generators let you preview layouts, resize windows dynamically, and see how the flex items adjust in real time."),
            ("Is there a fee or attribution required to use the CSS styles?", "No, all generated code, styling classes, and layout rules are 100% open-source and free to copy. You can use them for personal, academic, or commercial projects without attribution.")
        ]
    },
    "dev": {
        "intro": "Streamline your software development cycle with our high-speed formatters, minifiers, and encoders. Designed for developers who require quick parsing, structural verification, and size optimization of standard data formats.",
        "tech_details": "Our development utilities leverage browser-based JavaScript engines (like Google Chrome's V8) to process files and text. Encoders and minifiers run locally in sandboxed threads, ensuring your sensitive development configs, code tokens, and data payloads are never exposed to remote endpoints.",
        "use_cases": [
            "Beautifying unreadable JSON, HTML, or CSS code structures for debugging.",
            "Minifying source code scripts to optimize client load times and save bandwidth.",
            "Encoding/decoding API payloads via Base64 or URL protocols safely without leakage."
        ],
        "faqs": [
            ("Are my code configurations or sensitive JSON files uploaded to your servers?", "No. MultiTools Hub is built on a strict privacy-first architecture. All text transformation, JSON validation, and Base64 translations are processed locally in your browser cache. Zero bits of your files or text are sent to our hosts."),
            ("What happens if my JSON file has syntax errors?", "Our formatters and validators run syntactic parsers that highlight the exact character position and line number where a syntax break occurred, helping you locate missing commas or brackets instantly."),
            ("Is there a size limit on the source code I paste in?", "While the tool can parse files up to several megabytes, performance is determined by your local device's memory. For optimal speeds on large code blocks, we recommend closing unused browser tabs.")
        ]
    },
    "seo": {
        "intro": "Improve your site's visibility, metadata consistency, and indexing speed with our professional SEO and crawler management utilities. Ideal for marketing specialists, blog managers, and webmasters.",
        "tech_details": "These SEO tools parse website configurations, generate index directives, and check tags locally. Sitemaps and Robots rules are formulated instantly based on standards defined by Google and major search engines.",
        "use_cases": [
            "Generating search-engine compliant sitemaps to accelerate web indexation.",
            "Creating structured meta tags and open graph (OG) tags to improve search CTR and social sharing.",
            "Analyzing keyword distributions and headers to optimize pages for semantic search ranking."
        ],
        "faqs": [
            ("How do robots.txt generator files help my SEO?", "A robots.txt file guides search bots on which pages to crawl or avoid. Restricting crawlers from scanning administrative or private directories saves crawl budget and prevents duplicate indexation issues."),
            ("What are Open Graph tags, and why are they necessary?", "Open Graph (OG) tags are special meta tags that control how your website's preview card is displayed on platforms like Facebook, Twitter, and LinkedIn. A descriptive title and high-resolution image tag increase CTR by up to 150%."),
            ("Do your analyzers run live requests on remote websites?", "Certain analyzer tools evaluate local parameters client-side. For analyzers that inspect live URL meta tags, minor requests are funneled through secure cloud APIs purely to retrieve header schemas, without storing queries.")
        ]
    },
    "text": {
        "intro": "Enhance your editing, writing, and formatting workflows with our collection of text analytics and manipulation tools. Perfect for publishers, copywriters, and developers handling string formatting.",
        "tech_details": "Our text processors work directly in your browser's RAM, utilizing native JavaScript string functions for maximum speed. Since all changes occur in real-time on your client, your drafts, notes, and documents remain private.",
        "use_cases": [
            "Counting words, sentences, and character limits for platform compliance (like Twitter or metadata tags).",
            "Translating string cases (Title Case, UPPERCASE, Slug paths) for coding and editorial uniformity.",
            "Comparing two paragraphs to identify exact textual differences (Diff checking)."
        ],
        "faqs": [
            ("Can this counter count characters without spaces?", "Yes, our counters calculate total characters with and without space delimiters, giving you precise metrics for social media posts, SMS thresholds, and SEO requirements."),
            ("How secure is it to paste my private articles or notes here?", "100% secure. Because the page does not communicate with any database server during text manipulation, your copy remains inside your browser session and is lost immediately when you close or reload the tab."),
            ("Does the slug generator support international characters?", "Our slug generator strips special accents and symbols to convert strings into standard SEO-friendly URL formats (containing alphanumeric characters and dashes).")
        ]
    },
    "math": {
        "intro": "Solve calculation bottlenecks, unit conversions, and algebraic formulas with our collection of client-side math solvers and conversion utilities. Helpful for students, financial analysts, and programmers.",
        "tech_details": "Calculations and unit mappings are coded using high-precision JavaScript numeric libraries. Number bases (like Binary, Octal, Hex) are converted instantly in-memory without lag.",
        "use_cases": [
            "Calculating financial margins, discount percentages, and GST ratios for commerce.",
            "Converting units of length, weight, and temperature across standard scientific systems.",
            "Translating between numbering bases and Roman numerals for programming and engineering."
        ],
        "faqs": [
            ("Are the calculations mathematically precise?", "Yes, calculations use standard IEEE 754 floating-point arithmetic. For tools requiring extreme precision (like fractions or percentage scales), formulas are structured to minimize floating-point errors."),
            ("Does this calculator work offline?", "Yes. Once the page is loaded, the math scripts are cached locally, allowing you to run formulas, conversions, and percentage splits even when your internet connection is down."),
            ("Can I enter negative numbers or decimals?", "Yes, our forms are configured to accept standard signed numbers and decimal floats where mathematically appropriate.")
        ]
    },
    "security": {
        "intro": "Secure your data assets, validate credentials, and audit credential configurations with our local encryption, hashing, and token tools. Crucial for network administrators and privacy-minded users.",
        "tech_details": "Cryptographic utilities (including MD5, SHA-256, and password complexity estimators) run 100% client-side. Secret phrases and passwords never traverse the network, protecting your inputs from server logs and traffic inspection.",
        "use_cases": [
            "Generating strong, random passwords to protect digital accounts from dictionary attacks.",
            "Validating credit card format validity using the Luhn checksum formula locally.",
            "Creating secure cryptographic hashes for verification of data integrity."
        ],
        "faqs": [
            ("Is it safe to generate passwords on this website?", "Yes, because the password generator operates locally using secure random-number generators (`crypto.getRandomValues`) inside your browser. No strings are transmitted over the internet, preventing interception."),
            ("Does the credit card validator save or check my credit card numbers?", "No. The credit card checker runs the mathematical Luhn algorithm in-memory to confirm standard structural compliance (e.g. valid lengths and check digit). We do not check balances, nor do we store any card numbers."),
            ("What is the difference between hashing and encryption?", "Hashing (like SHA-256) is a one-way mathematical function. Once a string is hashed, it cannot be reversed. Encryption is a two-way process that requires a key to decrypt the original data.")
        ]
    },
    "time": {
        "intro": "Manage temporal transformations, timestamp adjustments, and countdown configurations with our local time conversions and tracking tools. Great for developers and remote workers.",
        "tech_details": "Datetime parsing uses local system clocks and browser timezones. Timestamps are translated using built-in Unix date logic inside client-side scripts.",
        "use_cases": [
            "Translating Unix timestamps into human-readable UTC/local date strings and vice versa.",
            "Calculating duration and elapsed days between calendar dates for deadlines.",
            "Tracking stopwatches and timer countdowns for productivity sprints."
        ],
        "faqs": [
            ("How does timezone conversion handle daylight saving time (DST)?", "The timezone tool utilizes the browser's native internationalization API (`Intl.DateTimeFormat`) which references the global IANA Time Zone Database to automatically resolve DST transitions."),
            ("What is a Unix epoch timestamp?", "A Unix timestamp represents the total number of seconds (or milliseconds) that have elapsed since January 1, 1970 (UTC), excluding leap seconds. It is a standard format for database systems."),
            ("Can I calculate days between dates across centuries?", "Yes, our calculator supports standard Gregorian calendar calculations spanning thousands of years, adjusting automatically for historical leap years.")
        ]
    },
    "web": {
        "intro": "Inspect page sources, test website redirects, trace DNS settings, and preview HTML elements with our sandbox web tools. A must-have for developers debugging network issues.",
        "tech_details": "Rendering preview engines load scripts in sandboxed frame containers. Network inspection queries utilize lightweight APIs to query registers (DNS, WHOIS) securely, outputting structural records in real-time.",
        "use_cases": [
            "Live previewing HTML and CSS snippet layouts safely in a sandbox.",
            "Checking domain registration info (WHOIS) and system DNS records (A, MX, TXT).",
            "Testing redirection hops and measuring loading speeds of URL assets."
        ],
        "faqs": [
            ("Why is my live HTML preview not executing external scripts?", "To maintain security and prevent cross-site scripting (XSS), our preview frame is sandboxed, blocking frame breakouts and certain local cookie storage actions."),
            ("Does the WHOIS tool lookup private registration details?", "The WHOIS tool returns public registration records provided by TLD registries. If a domain owner has enabled WHOIS privacy protection, the output will list proxy registrar contacts."),
            ("Is my IP address logged when I inspect a website status?", "No, domain inspections are processed via secure middle endpoints that check host records on our behalf, keeping your local IP anonymous to the destination host.")
        ]
    },
    "misc": {
        "intro": "Explore unique utilities including speech transcription, aspect ratio guides, color visualizers, and digital sketchpads to round out your utility toolkit.",
        "tech_details": "Advanced utilities interface with local device APIs (such as Speech Recognition and Audio Synthesis interfaces) inside modern browsers, requiring explicit microphone permissions only when requested.",
        "use_cases": [
            "Synthesizing text strings into spoken voice audio files (TTS).",
            "Calculating screen resolution specifications and visual aspect ratios.",
            "Sketching mockup drawings on a canvas and saving results as png images."
        ],
        "faqs": [
            ("Does the Speech-to-Text tool upload my voice recordings?", "No, transcription utilizes the Web Speech API which uses local browser engine processing. Your microphone stream is transcribed locally and never recorded or saved."),
            ("How do I save drawings from the digital drawing board?", "Once you finish drawing, click the export/download button. The tool captures the canvas state and prompts you to save it as a high-quality PNG image locally."),
            ("How do I calculate pixel dimensions using the aspect ratio tool?", "Simply enter your base width or height along with the desired ratio (e.g. 16:9), and the tool will calculate the matching pixel scale instantly.")
        ]
    },
    "pdf": {
        "intro": "Modify, merge, compress, and convert PDF documents in your browser with our client-side document processing suite. A secure alternative to heavy desktop PDF applications.",
        "tech_details": "PDF compilation, file splitting, and rotation are performed by high-performance JavaScript engines (like pdf-lib or WebAssembly builds of document libraries) operating entirely in your client RAM. Files never touch the cloud.",
        "use_cases": [
            "Merging multiple PDF scans into a single chronological document for filing.",
            "Compressing large PDF documents to optimize email attachments without losing text clarity.",
            "Encrypting files with password protection or unlocking non-copyright protected documents."
        ],
        "faqs": [
            ("Is there a limit on the file size of PDF uploads?", "Our tools run locally in browser memory, meaning size limits depend on your computer's RAM. We recommend files under 50MB for smooth, lag-free processing on standard machines."),
            ("Can I merge password-protected PDF files?", "You must unlock secured PDF documents first using our Unlock PDF tool before they can be merged or split with other files."),
            ("Are my sensitive contracts or financial PDFs secure here?", "Absolutely. We do not transfer your documents over the internet. The processing starts, runs, and finishes on your computer. This makes it safe for sensitive corporate and personal documents.")
        ]
    }
}

# Detailed Custom SEO texts for major tools to ensure maximum value
TOOL_SPECIFIC_SEO = {
    "json-formatter": """
        <h2>Professional JSON Formatting and Syntax Optimization</h2>
        <p>In modern web architectures, JavaScript Object Notation (JSON) is the universal format for API data transmission, configuration files, and state synchronization. However, raw JSON responses from API gateways are typically minified, strip out whitespace, and are difficult for developers to inspect. Our <strong>JSON Formatter</strong> provides a professional, instant resolution. It parses your nested JSON data and formats it with customizable tab indentation, making complex arrays and key-value pairs easy to read.</p>
        
        <h3>Local Syntax Validation & Visual Nesting</h3>
        <p>A single missing comma, unmatched bracket, or unescaped quote can break an entire configuration file or API request. Beyond beautifying text, our formatter runs a robust syntax parser in the background. If your JSON structure is malformed, our validator isolates the parsing error, pointing you directly to the offending line number. By visualizing nested hierarchies, you can map parent-child objects quickly and audit data configurations before deployment.</p>
        
        <h3>Zero Server Exposure for Sensitive API Keys</h3>
        <p>Many online formatters upload your inputs to external logs, posing a severe security risk if your payload contains private API keys, database user records, or customer transactions. MultiTools Hub is engineered on a strict <strong>client-side architecture</strong>. The formatting scripts process the pasted text entirely within your local browser memory. No data is sent to a server. This design guarantees compliance with corporate privacy standards and GDPR policies, allowing you to format production configs securely.</p>
    """,
    "word-counter": """
        <h2>Analyze Text Length, Word Metrics, and Reading Time Instantly</h2>
        <p>Writing for the web requires strict adherence to length constraints. Whether you are drafting a meta description (160 characters), a social media post, or a long-form article, keeping track of your metrics is essential. Our <strong>Word Counter</strong> is a fast, client-side utility that analyzes your drafts and outputs real-time counts for words, characters, sentences, and paragraphs, helping you optimize content for any platform.</p>
        
        <h3>Improving Readability and SEO Impact</h3>
        <p>Search engines value structured, readable articles. By monitoring your average sentence lengths and paragraph divisions, you can ensure your content remains readable for users. Our tool goes beyond counting to estimate average reading times, allowing bloggers and editors to structure content formats effectively. Paste your text, view stats immediately, and edit directly inside the input workspace.</p>
        
        <h3>Complete Privacy for Confidential Drafts</h3>
        <p>Writing sensitive business proposals, patent descriptions, or private letters requires a secure workspace. Our Word Counter runs entirely in your local RAM. We never transmit your text over the web, meaning your words stay private. There are no size restrictions or account requirements, making it the most convenient and secure counter on the web.</p>
    """,
    "password-generator": """
        <h2>Generate Cryptographically Strong Passwords Instantly</h2>
        <p>With cyber attacks and dictionary databases expanding daily, using simple passwords like 'password123' or repeating keys across websites is a security risk. Our <strong>Password Generator</strong> is a professional utility that constructs strong, random strings of characters that are virtually impossible to brute-force. Choose your length, toggle uppercase letters, numbers, and special symbols, and secure your digital identity.</p>
        
        <h3>How Secure Random Numbers Work Client-Side</h3>
        <p>Most basic online password generators use predictable math functions (`Math.random`) to select characters, which can sometimes be reverse-engineered by advanced algorithms. Our generator utilizes the cryptographically secure pseudorandom number generator (CSPRNG) API built into modern web browsers (`window.crypto`). This yields true randomness, ensuring that each password is safe for financial portals, email accounts, and database configurations.</p>
        
        <h3>Privacy-First Credential Creation</h3>
        <p>We do not collect, log, or store the passwords you generate. Because all code runs client-side, the generated credentials exist only on your screen and in your clipboard. Once you close the tab, all traces are deleted. Generate passwords with confidence, copy them with a single click, and protect your digital assets safely.</p>
    """,
    "keyword-density": """
        <h2>Analyze Keyword Frequency and Optimize Content for Search Engines</h2>
        <p>In search engine optimization, semantic relevance is key. If you repeat a search phrase too many times, search bots might flag your page for keyword stuffing. If you use it too rarely, search engines may fail to index your page for the query. Our <strong>Keyword Density Analyzer</strong> lets you paste your content and see a detailed breakdown of the most frequently used words and phrases, helping you write naturally while optimizing for rankings.</p>
        
        <h3>Writing for Search Generative Experience (SGE)</h3>
        <p>Modern search systems like Google's SGE look for natural language, structured explanations, and comprehensive answers. By analyzing single, double, and triple-word frequency loops, you can identify grammatical patterns, eliminate repetitive filler words, and balance keyword variations to make your articles read professionally for both AI and human reviewers.</p>
        
        <h3>Instant Analysis with Local Processing</h3>
        <p>We analyze your text right inside your browser window. No drafts are sent to server databases, protecting your unpublished articles, client copy, and content drafts. Simply copy your draft, run the density analyzer, and refine your copy to hit the sweet spot for search engines.</p>
    """,
    "meta-tag-generator": """
        <h2>Create SEO-Friendly HTML Meta Tags for Higher Rankings</h2>
        <p>Meta tags are snippets of code that tell search engines and social media networks what a webpage is about. Correctly formatted tags (including titles, descriptions, and Open Graph objects) are critical for SEO and click-through rates. Our <strong>Meta Tag Generator</strong> provides a simple, structured form that outputs fully compliant HTML tags in seconds.</p>
        
        <h3>Boost Search CTR and Social Sharing</h3>
        <p>If your website links are shared on Facebook or Twitter without Open Graph (OG) meta tags, they will display as bare links, which look uninviting. Our generator structures header attributes so that your posts display beautiful preview cards with custom image overlays and tags, improving engagement and trust. Simply fill out the details, copy the generated code, and paste it into your page headers.</p>
        
        <h3>Modern Standards with Clean Code Output</h3>
        <p>All output tags conform to current Google Webmaster guidelines and Open Graph protocols. The tool processes entries locally, generating code instantly in your workspace. Elevate your SEO workflow and ensure your site headers are configured for search success.</p>
    """
}

def get_seo_content(category, tool_id, title):
    """
    Returns structured, rich HTML content for a specific tool.
    Combines custom articles with category guidelines to produce unique guides.
    """
    # 1. Check specific database first (image or main)
    if tool_id in TOOL_SPECIFIC_SEO:
        custom_content = TOOL_SPECIFIC_SEO[tool_id]
    elif tool_id in IMAGE_SEO_DATA:
        custom_content = IMAGE_SEO_DATA[tool_id]
    else:
        # Generate custom programmatic SEO text based on title and category
        cat_data = CATEGORY_INFO.get(category.lower(), {
            "intro": "Experience high-performance online utilities designed to streamline your digital workflows.",
            "tech_details": "This utility operates locally in your browser memory for maximum performance and security.",
            "use_cases": ["Optimizing digital workflows.", "Processing data securely.", "Developer and designer tasks."],
            "faqs": [("Is it secure?", "Yes, all data is processed locally.")]
        })
        
        use_case_list = "".join([f"<li>{uc}</li>" for uc in cat_data["use_cases"]])
        
        faq_list = "".join([
            f"<div class='faq-item' style='margin-bottom: 25px;'>"
            f"<h4 style='color: var(--primary); margin-bottom: 10px;'>Q: {q}</h4>"
            f"<p style='color: var(--text-muted); line-height: 1.6;'>A: {a}</p>"
            f"</div>"
            for q, a in cat_data["faqs"]
        ])
        
        # Programmatically assemble a rich document to ensure 300+ words
        custom_content = f"""
        <h2>Comprehensive Guide to using {title} Online</h2>
        <p>Our <strong>{title}</strong> is a dedicated utility nested within our {category.upper()} suite at MultiTools Hub. This application is designed to solve common task bottlenecks by offering a responsive, high-speed, and intuitive interface. {cat_data["intro"]}</p>
        
        <h3>Key Applications and Use Cases</h3>
        <p>Whether you are a seasoned engineer or a casual web explorer, integrating this tool into your daily operations brings several benefits:</p>
        <ul style="color: var(--text-muted); margin-bottom: 30px; padding-left: 20px; line-height: 1.8;">
            {use_case_list}
        </ul>
        
        <h3>Under the Hood: Privacy & Performance</h3>
        <p>Privacy is the central design tenet of MultiTools Hub. {cat_data["tech_details"]} By eliminating server uploads, we block data interception, reduce page load times, and offer a tool that works regardless of bandwidth limits once cached. Standard security protocols are implemented to keep operations sandboxed.</p>
        
        <h3 style="margin-top: 40px; margin-bottom: 25px;">Frequently Asked Questions</h3>
        <div class="faq-container" style="background: rgba(255,255,255,0.01); border: 1px solid var(--border); border-radius: 20px; padding: 30px; margin-bottom: 40px;">
            {faq_list}
        </div>
        """
        
    return custom_content.strip()
